import type { Flower, OperationRecord, OutboundRecord, PackageTemplate, PackageUsageRecord } from '@/types';
import { generateId, getTodayDateString } from '@/utils/helpers';

export const initialFlowers: Flower[] = [
  {
    id: 'FL001',
    name: '白菊',
    type: '白菊',
    currentStock: 80,
    safeStock: 50,
    location: 'A区-01',
    status: '正常',
    createdAt: '2026-05-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'FL002',
    name: '黄菊',
    type: '黄菊',
    currentStock: 35,
    safeStock: 40,
    location: 'A区-02',
    status: '偏低',
    createdAt: '2026-05-01T00:00:00.000Z',
    updatedAt: '2026-06-02T00:00:00.000Z',
  },
  {
    id: 'FL003',
    name: '白百合',
    type: '白百合',
    currentStock: 0,
    safeStock: 30,
    location: 'B区-01',
    status: '缺货',
    createdAt: '2026-05-02T00:00:00.000Z',
    updatedAt: '2026-06-03T00:00:00.000Z',
  },
  {
    id: 'FL004',
    name: '粉百合',
    type: '粉百合',
    currentStock: 45,
    safeStock: 30,
    location: 'B区-02',
    status: '正常',
    createdAt: '2026-05-02T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'FL005',
    name: '康乃馨',
    type: '康乃馨',
    currentStock: 120,
    safeStock: 60,
    location: 'A区-03',
    status: '正常',
    createdAt: '2026-05-03T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'FL006',
    name: '白玫瑰',
    type: '白玫瑰',
    currentStock: 25,
    safeStock: 40,
    location: 'C区-01',
    status: '偏低',
    createdAt: '2026-05-03T00:00:00.000Z',
    updatedAt: '2026-06-02T00:00:00.000Z',
  },
];

export const initialRecords: OperationRecord[] = [
  {
    id: generateId(),
    flowerId: 'FL001',
    type: '补货',
    quantity: 50,
    date: getTodayDateString(),
    operator: '张三',
    remark: '日常补货',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    flowerId: 'FL002',
    type: '损耗',
    quantity: 5,
    date: getTodayDateString(),
    operator: '李四',
    remark: '花朵枯萎',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    flowerId: 'FL005',
    type: '补货',
    quantity: 80,
    date: getTodayDateString(),
    operator: '张三',
    remark: '节日备货',
    createdAt: new Date().toISOString(),
  },
];

export const initialOutboundRecords: OutboundRecord[] = [
  {
    id: generateId(),
    flowerId: 'FL001',
    flowerName: '白菊',
    flowerType: '白菊',
    quantity: 10,
    date: getTodayDateString(),
    recipient: '王家属',
    usage: '告别仪式',
    remark: '遗体告别仪式用花',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    flowerId: 'FL005',
    flowerName: '康乃馨',
    flowerType: '康乃馨',
    quantity: 5,
    date: getTodayDateString(),
    recipient: '李家属',
    usage: '追思会',
    remark: '追思会布置',
    createdAt: new Date().toISOString(),
  },
];

export const initialPackageTemplates: PackageTemplate[] = [
  {
    id: 'PKG001',
    name: '标准告别仪式花篮',
    type: '告别仪式花篮',
    description: '适用于遗体告别仪式的标准花篮，庄重大气',
    flowers: [
      { flowerId: 'FL001', flowerName: '白菊', quantity: 30 },
      { flowerId: 'FL003', flowerName: '白百合', quantity: 6 },
      { flowerId: 'FL008', flowerName: '满天星', quantity: 10 },
    ],
    createdBy: '管理员',
    createdAt: '2026-05-10T00:00:00.000Z',
    updatedAt: '2026-05-15T00:00:00.000Z',
  },
  {
    id: 'PKG002',
    name: '温馨追思会花束',
    type: '追思会花束',
    description: '温馨雅致的追思会花束，适合追思悼念场合',
    flowers: [
      { flowerId: 'FL005', flowerName: '康乃馨', quantity: 15 },
      { flowerId: 'FL004', flowerName: '粉百合', quantity: 5 },
      { flowerId: 'FL007', flowerName: '勿忘我', quantity: 8 },
    ],
    createdBy: '管理员',
    createdAt: '2026-05-12T00:00:00.000Z',
    updatedAt: '2026-05-20T00:00:00.000Z',
  },
  {
    id: 'PKG003',
    name: '简约日常祭扫套餐',
    type: '日常祭扫套餐',
    description: '简洁实用的日常祭扫用花套餐',
    flowers: [
      { flowerId: 'FL001', flowerName: '白菊', quantity: 10 },
      { flowerId: 'FL002', flowerName: '黄菊', quantity: 10 },
    ],
    createdBy: '张三',
    createdAt: '2026-05-18T00:00:00.000Z',
    updatedAt: '2026-05-25T00:00:00.000Z',
  },
];

export const initialPackageUsageRecords: PackageUsageRecord[] = [
  {
    id: generateId(),
    packageId: 'PKG001',
    packageName: '标准告别仪式花篮',
    packageType: '告别仪式花篮',
    date: getTodayDateString(),
    recipient: '陈家属',
    usage: '告别仪式',
    createdBy: '张三',
    remark: '陈老先生告别仪式',
    createdAt: new Date().toISOString(),
    items: [
      { flowerId: 'FL001', flowerName: '白菊', flowerType: '白菊', quantity: 30 },
      { flowerId: 'FL003', flowerName: '白百合', flowerType: '白百合', quantity: 6 },
      { flowerId: 'FL008', flowerName: '满天星', flowerType: '满天星', quantity: 10 },
    ],
  },
  {
    id: generateId(),
    packageId: 'PKG002',
    packageName: '温馨追思会花束',
    packageType: '追思会花束',
    date: getTodayDateString(),
    recipient: '刘家属',
    usage: '追思会',
    createdBy: '李四',
    remark: '刘女士追思纪念会',
    createdAt: new Date().toISOString(),
    items: [
      { flowerId: 'FL005', flowerName: '康乃馨', flowerType: '康乃馨', quantity: 15 },
      { flowerId: 'FL004', flowerName: '粉百合', flowerType: '粉百合', quantity: 5 },
      { flowerId: 'FL007', flowerName: '勿忘我', flowerType: '勿忘我', quantity: 8 },
    ],
  },
];
